proj:
  outputs:
    default:
      type: snowflake
      account: "**"         # Replace ** with your Snowflake account
      user: "**"               # Replace ** with your Snowflake username
      password: "**"       # Replace ** with your Snowflake password
      role: "**"               # Replace ** with your Snowflake role
      database: "**"        # Replace ** with your Snowflake database name
      warehouse: "**"     # Replace ** with your Snowflake warehouse name
      schema: analytics
      threads: 1
  target: default
